### PR TITLE
Enable Bitbucket cloning again

### LINKED ISSUE #2716: bitbucket git support
Receiving a 'SparkException: GitException(git.invalid_repo_url)' when trying to clone a private git repository from bitbucket.org

Would like to help fix/add this functionality, any pointers weclome

### PR DESCRIPTION
**Pull request by belak**
Closes #2716

See https://bitbucket.org/site/master/issues/6666/detect-git-requests-by-content-type-header#comment-24468616

### CODE REVIEW

**Comment by belak** [comment]
I signed it!

**Comment by AaronLayton** [comment]
:+1:  thanks again @belak

**Comment by ussuri** [comment]
Thanks a lot! LGTM

**Comment by AaronLayton** [comment]
@ussuri how long do you think before this update gets pushed to the Chrome App Store?

**Comment by ussuri** [comment]
I'll try to make some time to get it out by Monday.

**Comment by georgemck** [comment]
Hope there's a new build in store incorporating this pull request. It will be very much appreciated.

**Pull request merged**
