### PR TITLE
Update for polymer 1.0

### PR DESCRIPTION
**Pull request by ebidel**
R: @ussuri

### CODE REVIEW

**Comment by ussuri** [comment]
LGTM, and many thanks!

**Comment by ebidel** [comment]
Can you LMK when a new version of CDE will be on the store that would have this change? We're looking to use CDE at the Polymer Summit in Sept and codelab authors are already starting to write content.

**Comment by ussuri** [comment]
Will do!

**Comment by ussuri** [comment]
The build has failed, but I'm in a crunch with my main project right now,
so I'll deal with this sometime next week.

**Comment by ebidel** [comment]
Np. Thanks for getting back to me.

**Pull request merged**
